### ISSUE TITLE
manual vs instant seal mode

### ISSUE THREAD

**Issue by pgherveou** [inkdevhub/swanky-node#70]
# Description
There are no options right now to start the node in "manual seal" mode, where a block is authored on demand when the user 
fire a call to the `engine_createBlock` endpoint.

My understanding is that we create a block whenever we fire a call to this RPC or when a transaction is created.

## Required Tasks

To create a block on demand, we would need to update that part of the code, we would need to add a new option or environment flag to the client, to setup the command_stream defined in [service.rs](https://github.com/AstarNetwork/swanky-node/blob/main/node/src/service.rs) as such:

```rs
let commands_stream = if instant_seal {
    stream::select(rpc_commands_stream, pool_import_commands_stream);
} else {
    rpc_commands_stream;
}
```
Please let me know if I missed something or if there is an easier way to enable this

**Comment by shunsukew** [comment]
Both manual seal via RPC and instant seal is enabled at the same time (at this line https://github.com/AstarNetwork/swanky-node/blob/a0da15772d48035426f2ed241a31d473534a6839/node/src/service.rs#L219C6-L219C21)

Do you mean having a feature to let users to run swanky-node with only manual seal mode without instant seal?
